version: '3.1'

services:
  ui:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      DB_URL: mongodb://mongo/vidly
    entrypoint: ./docker-entrypoint.sh
  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017 #
      - 27019:27017

  dbui:
    image: mongo-express # conatiner image
    ports:
      - 8081:8081 # published ports
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    