apiVersion: apps/v1 
kind: ReplicaSet

metadata:
  name: nginx-rs
  labels:
    app: my-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: my-app-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest



